"""Mock LLM responses and API errors for E2E testing."""

MOCK_LLM_RESPONSES = {
    "executive_summary": """
Experienced software engineer with 5+ years of full-stack development expertise.
Proven track record in designing scalable backend systems and RESTful APIs.
Strong proficiency in Python, cloud technologies, and agile development practices.
Passionate about delivering high-quality solutions and mentoring junior developers.
""",
    
    "experience_bullets": """
• Designed and implemented scalable microservices architecture serving 1M+ users
• Developed RESTful APIs with 99.9% uptime and sub-200ms response times
• Led cross-functional team of 5 engineers in agile development environment
• Optimized database queries resulting in 40% performance improvement
• Implemented CI/CD pipelines reducing deployment time from hours to minutes
• Mentored 3 junior developers and conducted technical interviews
• Collaborated with product managers on feature requirements and technical roadmap
""",
    
    "technical_skills": """
**Programming Languages:** Python, JavaScript, TypeScript, Java, Go
**Backend Technologies:** Django, FastAPI, Node.js, Express, Spring Boot
**Frontend Technologies:** React, Vue.js, Angular, HTML5, CSS3
**Databases:** PostgreSQL, MongoDB, Redis, MySQL, Elasticsearch
**Cloud Platforms:** AWS (EC2, S3, RDS, Lambda), Docker, Kubernetes
**DevOps Tools:** Jenkins, GitLab CI, Terraform, Prometheus, Grafana
**Development Tools:** Git, VS Code, IntelliJ, Postman, Jira
""",
    
    "projects": """
**E-commerce Platform Redesign**
• Led complete redesign of legacy e-commerce platform using microservices architecture
• Implemented real-time inventory management and order processing system
• Achieved 99.9% uptime with automated monitoring and alerting
• Reduced page load times by 60% through performance optimization
• Technologies: Python, Django, React, PostgreSQL, Redis, AWS

**Real-time Analytics Dashboard**
• Developed comprehensive analytics platform for business intelligence
• Implemented real-time data processing pipeline handling 1TB+ daily
• Created interactive dashboards with role-based access control
• Integrated with multiple data sources and third-party APIs
• Technologies: Python, FastAPI, React, D3.js, Kafka, Elasticsearch
""",
    
    "generic_response": """
This is a generic mock response for testing purposes. It contains relevant
information that would typically be generated by an LLM for CV content.
The response is structured and professional, suitable for CV sections.
""",
    
    "big_10_skills": {
        "raw_output": """
Based on the job description analysis, here are the top 10 technical skills:

1. Python Programming - Core requirement, mentioned multiple times
2. RESTful API Development - Essential for backend systems
3. Database Design & Optimization - PostgreSQL, MongoDB expertise needed
4. Cloud Platform Experience - AWS, GCP, Azure proficiency
5. Containerization - Docker and Kubernetes experience
6. Microservices Architecture - Scalable system design
7. CI/CD Pipeline Implementation - DevOps practices
8. Version Control - Git proficiency
9. Agile Development Methodologies - Team collaboration
10. Problem-solving & Communication - Soft skills emphasis
""",
        "structured_skills": [
            {
                "skill": "Python Programming",
                "relevance_score": 0.95,
                "justification": "Core requirement mentioned multiple times in job description"
            },
            {
                "skill": "RESTful API Development",
                "relevance_score": 0.90,
                "justification": "Essential for backend systems development"
            },
            {
                "skill": "Database Design & Optimization",
                "relevance_score": 0.85,
                "justification": "PostgreSQL and MongoDB expertise specifically mentioned"
            },
            {
                "skill": "Cloud Platform Experience",
                "relevance_score": 0.85,
                "justification": "AWS, GCP, Azure proficiency required"
            },
            {
                "skill": "Containerization",
                "relevance_score": 0.80,
                "justification": "Docker and Kubernetes experience mentioned"
            },
            {
                "skill": "Microservices Architecture",
                "relevance_score": 0.80,
                "justification": "Scalable system design is key responsibility"
            },
            {
                "skill": "CI/CD Pipeline Implementation",
                "relevance_score": 0.75,
                "justification": "DevOps practices mentioned as nice to have"
            },
            {
                "skill": "Version Control (Git)",
                "relevance_score": 0.75,
                "justification": "Essential development tool"
            },
            {
                "skill": "Agile Development Methodologies",
                "relevance_score": 0.70,
                "justification": "Team collaboration and agile practices mentioned"
            },
            {
                "skill": "Problem-solving & Communication",
                "relevance_score": 0.70,
                "justification": "Soft skills explicitly mentioned as requirements"
            }
        ]
    },
    
    "quality_assurance_feedback": {
        "overall_score": 0.85,
        "feedback": "The CV content is well-structured and relevant to the job requirements. Minor improvements needed in quantifying achievements.",
        "suggestions": [
            "Add more specific metrics to quantify achievements",
            "Include relevant keywords from job description",
            "Ensure consistent formatting across all sections"
        ],
        "approved": True
    },
    
    "research_findings": {
        "company_info": "TechCorp is a leading technology company specializing in cloud solutions and enterprise software.",
        "industry_trends": "Current trends include microservices adoption, cloud-native development, and AI/ML integration.",
        "key_technologies": ["Python", "Kubernetes", "AWS", "Microservices", "DevOps"]
    }
}

MOCK_API_ERRORS = {
    "rate_limit": {
        "type": "rate_limit",
        "message": "Rate limit exceeded. Please try again later.",
        "retry_after": 60
    },
    "timeout": {
        "type": "timeout",
        "message": "Request timed out after 30 seconds",
        "retry_after": 5
    },
    "authentication": {
        "type": "authentication",
        "message": "Invalid API key or authentication failed",
        "retry_after": None
    },
    "api_error": {
        "type": "api_error",
        "message": "Internal server error occurred",
        "retry_after": 10
    },
    "quota_exceeded": {
        "type": "quota_exceeded",
        "message": "Monthly quota exceeded",
        "retry_after": None
    },
    "service_unavailable": {
        "type": "service_unavailable",
        "message": "Service temporarily unavailable",
        "retry_after": 30
    }
}